name: build

on:
  push:
    branches:
      - 'main'
      - '**-ci'
  workflow_dispatch: null

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Build
        run: |
          make luajit
          make LUA_LIB=luajit all
      -
        name: Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux
          path: |
            devi
            build/devi.so
  macos:
    runs-on: macos-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Build
        run: |
          make luajit
          make LUA_LIB=luajit all
      -
        name: Artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos
          path: |
            devi
            build/devi.dylib
  windows:
    runs-on: windows-2022
    defaults:
      run:
        shell: msys2 {0}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64
          update: true
          install: git mingw-w64-x86_64-gcc mingw-w64-x86_64-cmake make unzip mingw-w64-x86_64-boost mingw-w64-x86_64-glm zip
      -
        name: Build code
        run: |
          make luajit
          make LUA_LIB=:lua51.dll all
      -
        name: Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows
          path: |
            devi
            build/devi.dll